clone:
  depth: full
pipelines:
  default:
    - step:
        script:
          - git push --mirror git@github.com:ktatar/rawmusicfromfreemovements.git
          - git push --mirror git@github.coventry.ac.uk:ad5041/RawMusicFromFreeMovements.git